name: "CI"
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  checks:
    runs-on: ${{ matrix.system }}
    permissions:
      contents: read
    strategy:
      matrix:
        system: [ x86_64-linux, aarch64-darwin, x86_64-darwin ]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: nixci --extra-access-tokens ${{ secrets.GITHUB_TOKEN }} build --systems "${{ matrix.system }}"
      - name: Run
        run: nix --option system ${{ matrix.system }} run
        if: "!(matrix.system == 'x86_64-darwin')"  # Skip rosetta runs (that will fail anyway)
